name: Publish changes to Angular package
on:
  release:
    types: [created]
jobs:
  check-readme-and-changelog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Check for changes in readme and changelog files
        run: |
          if ! git diff --quiet HEAD~ HEAD -- README.md CHANGELOG.md; then
            echo "README and/or CHANGELOG have been modified. Proceeding with deployment."
          else
            echo "README and/or CHANGELOG have not been modified. Terminating deployment."
            exit 1
          fi

      - name: Push build status to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        if: always()
  publish:
    needs: check-readme-and-changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/

      - name: Install Node.js dependencies
        run: npm ci

      - name: Publish to NPM
        run: |
          cd dist/flutterwave-angular-v3
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}

      - name: Push build status to Slack
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          MATRIX_CONTEXT: ${{ toJson(matrix) }}
        if: always()
